public class StudentBuild // user class
{
	public static void main(String[] args)
	{
		// set static fields
		Student.setClassName("Texts and Contexts");
		Student.setClassNumber("R06");
		Student.setInstructor("Prof. Franz");		

		// large constructor 
		Student s1 = new Student("Claire", "Yustat", "316 Arthur Ave", "Bronx", "NY", "cyustat@fordham.edu");
		Student s2 = new Student("Polina", "Bolberova", "111 E Fordham Rd", "Bronx", "NY", "pbolberov@fordham.edu");
		Student s3 = new Student("Emily", "Ruegger", "18 Patriots Rd", "Bronx", "NY", "eruegger@fordham.edu");

		// small constructor 
		Student s4 = new Student("Grace", "Cook"); 
		Student s5 = new Student("Grace", "McLees"); 

		// output students
		System.out.println(s1.toString());
		System.out.println();
		System.out.println(s2.toString());
		System.out.println();
		System.out.println(s3.toString());
		System.out.println();
		System.out.println(s4.toString());
		System.out.println();
		System.out.println(s5.toString());
		System.out.println();

		// use some getters & setters
		Student.setClassName("Java Programming");

		s4.setAddress("5 Martin Ln");
		s4.setCity("Manhattan");
		s4.setState("NY");
		s4.setEmail("gcook@fordham.edu");

		s5.setAddress("50 Cent Ave");
		s5.setCity("Bronx");
		s5.setState("NY");
		s5.setEmail("gmclees@fordham.edu");

		String firstName2 = s2.getFirstName();
		String lastName2 = s2.getLastName();
		System.out.println(firstName2 + " " + lastName2);
		System.out.println();

		String address3 = s3.getAddress();
		System.out.println(address3);
		System.out.println();

		s1.setAddress(address3);

		// output students again
		System.out.println(s1.toString());
		System.out.println();
		System.out.println(s2.toString());
		System.out.println();
		System.out.println(s3.toString());
		System.out.println();
		System.out.println(s4.toString());
		System.out.println();
		System.out.println(s5.toString());
	}
}

class Student // service class
{
	// static fields
	private static String classNumber;
	private static String className;
	private static String instructor;
	static int studentCount = 1000; // counter used for studentId

	// instance fields
	private int studentId;
	private String firstName;
	private String lastName;
	private String address;
	private String city;
	private String state;
	private String email;

	// constructor #1
	Student(String first, String last)
	{
		firstName = first;
		lastName = last;

		studentId = studentCount;

		studentCount++; // increment count
	}

	// constructor #2
	Student(String first, String last, String address, String city, String state, String email)
	{	
		this(first, last);

		this. address = address;
		this.city = city;
		this.state = state;
		this.email = email;
	}

	// STATIC getter/setter methods

	// classNumber
	static String getClassNumber() // getter
	{
		return(classNumber);
	}
	static void setClassNumber(String classNum) // setter
	{
		classNumber = classNum;
	}

	// className
	static String getClassName() // getter
	{
		return(className);
	}
	static void setClassName(String classNa) // setter
	{
		className = classNa;
	}

	//instructor
	static String getInstructor() // getter
	{
		return(instructor);
	}
	static void setInstructor(String in)
	{
		instructor = in;
	}

	// INSTANCE getter/setter methods
	
	// studentId
	int getStudentId() //getter
	{
		return(studentId);
	}
	// no studentId setter needed, generated by constructors

	// firstName
	String getFirstName() // getter
	{
		return(firstName);
	}
	void setFirstName(String fName) // setter
	{
		firstName = fName;
	}

	// lastName
	String getLastName() // getter
	{
		return(lastName);
	}
	void getLastname(String lName) // setter
	{
		lastName = lName;
	}

	// address
	String getAddress() // getter
	{
		return(address);
	}
	void setAddress(String a) // setter
	{
		address = a;
	}

	// city
	String getCity() // getter
	{
		return(city);
	}
	void setCity(String c) // setter
	{
		city = c;
	}

	// state
	String getState() // getter
	{
		return(state);
	}
	void setState(String s) // setter
	{
		state = s;
	}

	// email
	String getEmail() // getter
	{
		return(email);
	}
	void setEmail(String e) // setter
	{
		email = e;
	}

	// toString() method
	public String toString()
	{
		String data = 	"Student Name: " + firstName + " " + lastName + "\n" +
						"Student I.D.: " + studentId  + "\n" +
						"Class Name: " + className + "\n" +
						"Instructor Name: " + instructor + "\n" +
						"Class Number: " + classNumber + "\n" +
						"Student Address: " + address + ", " + city + ", " + state + "\n" +
						"Student Email Address: " + email;
		return(data);
	}
}