public class Student // service class
{
	// static fields
	private static String classNumber;
	private static String className;
	private static String instructor;
	static int studentCount = 1000; // counter used for studentId

	// instance fields
	private int studentId;
	private String firstName;
	private String lastName;
	private String address;
	private String city;
	private String state;
	private String email;

	// constructor #1
	Student(String first, String last)
	{
		firstName = first;
		lastName = last;

		studentId = studentCount;

		studentCount++; // increment count
	}

	// constructor #2
	Student(String first, String last, String address, String city, String state, String email)
	{	
		this(first, last);

		this. address = address;
		this.city = city;
		this.state = state;
		this.email = email;
	}

	// STATIC getter/setter methods

	// classNumber
	static String getClassNumber() // getter
	{
		return(classNumber);
	}
	static void setClassNumber(String classNum) // setter
	{
		classNumber = classNum;
	}

	// className
	static String getClassName() // getter
	{
		return(className);
	}
	static void setClassName(String classNa) // setter
	{
		className = classNa;
	}

	//instructor
	static String getInstructor() // getter
	{
		return(instructor);
	}
	static void setInstructor(String in)
	{
		instructor = in;
	}

	// INSTANCE getter/setter methods
	
	// studentId
	int getStudentId() //getter
	{
		return(studentId);
	}
	// no studentId setter needed, generated by constructors

	// firstName
	String getFirstName() // getter
	{
		return(firstName);
	}
	void setFirstName(String fName) // setter
	{
		firstName = fName;
	}

	// lastName
	String getLastName() // getter
	{
		return(lastName);
	}
	void getLastname(String lName) // setter
	{
		lastName = lName;
	}

	// address
	String getAddress() // getter
	{
		return(address);
	}
	void setAddress(String a) // setter
	{
		address = a;
	}

	// city
	String getCity() // getter
	{
		return(city);
	}
	void setCity(String c) // setter
	{
		city = c;
	}

	// state
	String getState() // getter
	{
		return(state);
	}
	void setState(String s) // setter
	{
		state = s;
	}

	// email
	String getEmail() // getter
	{
		return(email);
	}
	void setEmail(String e) // setter
	{
		email = e;
	}

	// toString() method
	public String toString()
	{
		String data = 	"Student Name: " + firstName + " " + lastName + "\n" +
						"Student I.D.: " + studentId  + "\n" +
						"Class Name: " + className + "\n" +
						"Instructor Name: " + instructor + "\n" +
						"Class Number: " + classNumber + "\n" +
						"Student Address: " + address + ", " + city + ", " + state + "\n" +
						"Student Email Address: " + email;
		return(data);
	}
}